
# このファイルは dbt プロジェクトの設定ファイルです（初心者コース用）。
# dbt on Snowflake での実行に必要な構成をすべて定義しています。

name: 'analytics_web_events'
version: '1.0.0'
config-version: 2

# Project Meta: プロジェクト全体のメタデータ
profile: 'snowflake'

# Model Paths: モデルファイルの場所
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Seeds: CSV データをテーブルに変換する設定
seeds:
  analytics_web_events:
    +schema: staging
    +materialized: table

# Models: デフォルト設定
models:
  analytics_web_events:
    # =====================================
    # STAGING レイヤー
    # =====================================
    # 目的：生データの軽い加工、カラム名/型の標準化
    # Materialization：VIEW（軽量、最新データ）
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]

    # =====================================
    # MARTS レイヤー
    # =====================================
    # 目的：ビジネス向けの最終データマート
    # Materialization：TABLE（パフォーマンス重視）
    marts:
      +materialized: table
      +tags: ["marts"]
      +schema: marts

# Tests: テスト設定
tests:
  store_failures: true  # テスト失敗時に失敗レコードを保存

# On-Build Hooks: dbt build 実行時の事前処理
on-run-start:
  - "{{ log('Starting dbt run', info=true) }}"

# On-Build Hooks: dbt build 実行完了時の事後処理
on-run-end:
  - "{{ log('Completed dbt run', info=true) }}"
